# Generated by Django 2.0.7 on 2018-07-10 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='作者名字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='CarouselPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('url', models.CharField(max_length=128, verbose_name='分类地址')),
                ('slug', models.CharField(default='', max_length=16, verbose_name='子链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '二级分类',
                'verbose_name': '二级分类',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('url', models.CharField(max_length=128, verbose_name='分类地址')),
                ('slug', models.CharField(default='', max_length=16, verbose_name='子链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '一级分类',
                'verbose_name': '一级分类',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrace', models.CharField(choices=[('d_dang', '当当'), ('j_dong', '京东'), ('t_mao', '天猫'), ('china_book', '中国图书')], max_length=16, verbose_name='所属平台')),
                ('url', models.CharField(max_length=512, verbose_name='详情页地址')),
                ('price', models.FloatField(default=0, verbose_name='原来价格')),
                ('sellPrice', models.FloatField(default=0, verbose_name='销售价')),
                ('discount', models.FloatField(default=10, verbose_name='折扣')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '商品价格',
                'verbose_name': '商品价格',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='商品名称')),
                ('image', models.ImageField(default='', upload_to='image', verbose_name='封面图')),
                ('four_name', models.CharField(default='', max_length=128, verbose_name='四级分类')),
                ('four_url', models.CharField(default='', max_length=128, verbose_name='四级分类')),
                ('author_name', models.CharField(default='', max_length=120, verbose_name='作者')),
                ('publisher', models.CharField(default='', max_length=512, verbose_name='出版社')),
                ('pub_time', models.DateField(default='', verbose_name='出版时间')),
                ('open', models.CharField(default='', max_length=512, verbose_name='开本')),
                ('page', models.IntegerField(default='', verbose_name='页数')),
                ('startWrap', models.FloatField(default=5, verbose_name='读者评分')),
                ('ISBN', models.CharField(default='', max_length=20, verbose_name='ISBN号')),
                ('code', models.CharField(default='', max_length=32, verbose_name='条形码')),
                ('ZhuangZhen', models.CharField(default='暂无', max_length=64, verbose_name='装帧')),
                ('BanCi', models.CharField(default='暂无', max_length=64, verbose_name='版次')),
                ('CeShu', models.CharField(default='暂无', max_length=64, verbose_name='册数')),
                ('ZhongLiang', models.CharField(default='暂无', max_length=64, verbose_name='重量')),
                ('YinShuaCiShu', models.CharField(default='暂无', max_length=64, verbose_name='印刷次数')),
                ('specialist', models.TextField(default='', verbose_name='本书特色')),
                ('brief', models.TextField(default='', verbose_name='内容简介')),
                ('excerpt', models.TextField(default='', verbose_name='作者简介')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('sku', models.IntegerField(default=0, verbose_name='库存')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('support', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '商品管理',
                'verbose_name': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='出版社名字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='书名')),
            ],
            options={
                'verbose_name_plural': '出版社',
                'verbose_name': '出版社',
            },
        ),
        migrations.CreateModel(
            name='TagAndProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name_plural': '商品/分类标签',
                'verbose_name': '商品/分类标签',
            },
        ),
        migrations.CreateModel(
            name='TagPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('url', models.CharField(max_length=128, verbose_name='分类地址')),
                ('slug', models.CharField(default='', max_length=16, verbose_name='子链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='父类')),
            ],
            options={
                'verbose_name_plural': '三级分类',
                'verbose_name': '三级分类',
            },
        ),
        migrations.AddField(
            model_name='tagandproduct',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TagPro', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='关联商品'),
        ),
        migrations.AddField(
            model_name='category',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ParentCategory', verbose_name='父类'),
        ),
        migrations.AddField(
            model_name='carouselpro',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='关联商品'),
        ),
        migrations.AddField(
            model_name='author',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='书名'),
        ),
    ]
