# Generated by Django 2.0.7 on 2018-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.TextField(default='', verbose_name='目录'),
        ),
        migrations.AddField(
            model_name='product',
            name='recomand',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='product',
            name='xiangguan',
            field=models.TextField(default='', verbose_name='相关资料'),
        ),
        migrations.AddField(
            model_name='product',
            name='zuozhejianjie',
            field=models.TextField(default='', verbose_name='作者简介'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ISBN',
            field=models.CharField(default='', max_length=64, verbose_name='ISBN号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=128, verbose_name='条形码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.TextField(default='', verbose_name='内容节选'),
        ),
        migrations.AlterField(
            model_name='product',
            name='page',
            field=models.CharField(default='', max_length=64, verbose_name='页数'),
        ),
    ]
