# Generated by Django 2.0.7 on 2018-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
