# Generated by Django 2.0.7 on 2018-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartproduct_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='commit_target',
            field=models.CharField(default='', max_length=32, verbose_name='结算标识符'),
        ),
    ]
