# Generated by Django 2.0.7 on 2018-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartproduct_commit_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='commit_target',
            field=models.CharField(default='', max_length=36, verbose_name='结算标识符'),
        ),
    ]
