"""
Django settings for ShopPro project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
import djcelery

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
sys.path.insert(0, os.path.join(BASE_DIR, "apps_others"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_!g@%q(1q5yj$-(5e(#52uw!wgm!vf&i4a79om9%n=2+w5v#%q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 用户新建APP
    "user",  # 用户
    "product",  # 产品
    "order",  # 订单/物流
    "cart",  # 购物车
    "comment",  # 评论
    "help",  # 帮助管理系统
    # 使用xadmin后台管理框架替换掉admin
    'xadmin',
    'crispy_forms',
    'reversion',
    # 富文本编辑
    'DjangoUeditor',
    # 分页
    'pure_pagination',
    # 异步操作
    "djcelery",
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',  # 缓存站点
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',  # 必须设置在最后一个位置

]

ROOT_URLCONF = 'ShopPro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'apps_others/xadmin/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # MEDIA图片处理
                # 'django.template.context_processors.media',
                # 设置全局变量 一级分类
                'apps_others.utils.globle_varible.varible',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShopPro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "shoppro",
        "HOST": "****",
        "PORT": 3306,
        "USER": "root",
        "PASSWORD": "****",
    }
}
# 缓存数据
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # 'LOCATION': 'redis://59.110.230.99:6379',
        'LOCATION': 'redis://127.0.0.1:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "zhujie165102",
        },
    },
}
# 添加缓存配置
CACHE_MIDDLEWARE_ALIAS = 'default'  # 用来存储的缓存别名
CACHE_MIDDLEWARE_SECONDS = 3  # 所有页面默认缓存时间,默认600
# CACHE_MIDDLEWARE_KEY_PREFIX = '47.98.205.93'  # 关键的前缀，当多个站点使用同一个配置的时候，这个可以设置可以避免发生冲突,一般设置为网站域名
# CACHE_MIDDLEWARE_ANONYMOUS_ONLY = False  # 那么只有匿名的请求会被缓存，这是一个禁用缓存非匿名用户页面的最简单的做法，注意确保已经启用了Django用户认证中间件

REDIS_TIMEOUT = 7 * 24 * 60 * 60
CUBES_REDIS_TIMEOUT = 60 * 60
NEVER_REDIS_TIMEOUT = 365 * 24 * 60 * 60

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
# 数据库存储使用时间，True时间会被存为UTC的时间
USE_TZ = False

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# if DEBUG:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# if not DEBUG:
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "apps_others/xadmin/static"),
)

# 设置我们上传文件的路径
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 发送邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "jakejie@163.com"  # "lq65535"  #
EMAIL_HOST_PASSWORD = "zhujie165102"  # "ly651822"  #
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_FROM = "jakejie@163.com"

ACTIVATE_HOST = "shop.jakejie.com"
# 邮件异步发送配置
djcelery.setup_loader()
CELERY_BROKEN_URL = 'redis://127.0.0.1:6379/1'
# BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = True
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TIMEZONE = 'Asia/Shanghai'

# 此处重载是为了使我们的UserProfile生效
AUTH_USER_MODEL = "user.UserProfile"

# # 设置邮箱和用户名均可登录
# AUTHENTICATION_BACKENDS = (
#     'user.views.CustomBackend',
# )
# 分页的设置
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10,  # 是总共会显示多少个page。(包括省略号，包括两边和中间)
    'MARGIN_PAGES_DISPLAYED': 2,  # 是旁边会显示多少个。
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,  # 当输入页数不合法是否要跳到第一页
}
# 每页显示多少数据
PAGE_SETTING = 2
# 支付宝配置参数
ALIPAY_APPID = "2016091400507425"
ALIPAY_URL = "https://openapi.alipaydev.com/gateway.do"
HOST = "http://shop.jakejie.com"
