# Generated by Django 2.0.7 on 2018-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='000000', max_length=10, verbose_name='邮编'),
        ),
    ]
