# Generated by Django 2.0.7 on 2018-07-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentType', models.CharField(choices=[('快递', 'express'), ('无需物流', 'no'), ('线下交易', 'under_line'), ('其他', 'other')], max_length=16, verbose_name='发货方式')),
                ('name', models.CharField(default='', max_length=200, verbose_name='物流公司')),
                ('num', models.CharField(default='0', max_length=32, verbose_name='快递单号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
            ],
            options={
                'verbose_name_plural': '物流管理',
                'verbose_name': '物流管理',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
            ],
            options={
                'verbose_name_plural': '订单详情商品',
                'verbose_name': '订单详情商品',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='订单号')),
                ('totleNum', models.IntegerField(verbose_name='总商品数量')),
                ('totlePrice', models.FloatField(verbose_name='总金额')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
            ],
            options={
                'verbose_name_plural': '订单管理',
                'verbose_name': '订单管理',
            },
        ),
    ]
