# Generated by Django 2.0.7 on 2018-07-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderList', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='orderNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderList', verbose_name='订单号'),
        ),
    ]
