# Generated by Django 2.0.7 on 2018-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180710_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderNum',
            field=models.CharField(max_length=32, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order',
            field=models.CharField(max_length=32, verbose_name='订单号'),
        ),
    ]
