# Generated by Django 2.0.7 on 2018-07-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180728_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='totleNum',
            new_name='totalNum',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='totlePrice',
            new_name='totalPrice',
        ),
    ]
