# Generated by Django 2.0.7 on 2018-07-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180728_1504'),
        ('order', '0005_auto_20180728_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='订单收货地址'),
        ),
    ]
