# Generated by Django 2.0.7 on 2018-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderlist_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='pay_method',
            field=models.CharField(default='', max_length=20, verbose_name='支付方式'),
        ),
    ]
