# Generated by Django 2.0.7 on 2018-07-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderlist_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='订单收货地址'),
        ),
    ]
